# Generated by Django 4.2.4 on 2023-08-12 20:08

from django.db import migrations

from django.db import migrations

import csv

def create_store_data(apps, schema_editor):
    Store = apps.get_model('store', 'Store')
    with open('store/csv_data/data.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            print(row)
            Store.objects.create(
                store_id=row['store_id'],
                timezone_str=row['timezone_str'],
            )

def populate_store_start_end_time(apps, schema_editor):
    Store = apps.get_model('store', 'Store')
    StoreTiming = apps.get_model('store', 'StoreTiming')
    with open('store/csv_data/Menu_hours.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            print(row)
            store = Store.objects.filter(store_id=row['store_id']).first()
            if store:
                store_timing = StoreTiming.objects.create(
                    store=store,
                    day=row['day'],
                    start_time=row['start_time_local'],
                    end_time=row['end_time_local'],
                )
                print(store_timing)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_store_data,reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_store_start_end_time,reverse_code=migrations.RunPython.noop),
    ]
